name: Build
on:
  workflow_call:
jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo "Project built successfully!"

  set-label:
    name: Set build-passed label
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Set build-passed label
        if: ${{ needs.build.result == 'success' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
              labels: ['build-passed']
            })