name: Version update and Docker push pipeline

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - release
        
env:
  NAME_VERSION_FILE: ${{ github.workspace }}/version
  RELEASE_BRACH: release
  MINOR: minor
  PATCH: patch
  VERSION_UPDATE_SCRIPT: .github/workflows/version_up.py
  REPO_NAME: ${{ github.event.repository.name }}
  PR_NUMBER: ${{ github.event.number }}
  URL_REPO: ${{ github.server_url }}/${{ github.repository }}
  DOCKER_REPO: ${{ secrets.DOCKERHUB_LOGIN }}/${{ github.repository.name }}

jobs:
  pre-merge-check:
    name: Print information
    runs-on: ubuntu-latest
    steps:
      - name: Branch Names
        id: branch-names
        uses: tj-actions/branch-names@v8.0.1
      
      - name: Print info about repo
        id: repo-info
        run: |
          echo "EVENT NAME    : ${{ github.event_name }}"
          echo "ACTION        : ${{ github.event.action }}"
          echo "IS            : ${{ github.event.pull_request.merged }}"
          echo "CURRENT BRANCH: ${{ steps.branch-names.outputs.current_branch }}"
          echo "REF           : ${{ github.ref }}"
          echo "REF NAME      : ${{ github.ref_name }}"
          echo "DEFAULT BRANCH: ${{ steps.branch-names.outputs.default_branch }}"
          echo "WOKSPACE      : ${{ github.workspace }}"
  
  security: 
    name: (SEC)
    needs: pre-merge-check
    uses: GnomeShift/lan_devops/.github/workflows/sec.yml@release
  
  update-version:
    name: (VER) Update version
    needs: security
    runs-on: ubuntu-latest
    outputs:
      tag: ${{steps.get-commit-txt.outputs.TAG_MSG}}
    steps:      
      - name: Get branch names
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Сheckout on [${{env.RELEASE_BRACH}}]
        uses: actions/checkout@v2
      
      - name: Print catalog info
        run : |
          echo "path to version file ${{ env.NAME_VERSION_FILE }}"
          
      - name: Install and Setup python 
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Update version [minor]
        if: startsWith(steps.branch-names.outputs.current_branch,'feature')
        run: 
          python ${{env.VERSION_UPDATE_SCRIPT}} ${{ env.NAME_VERSION_FILE }} ${{ env.MINOR }}

      - name: Update version [patch]
        if: startsWith(steps.branch-names.outputs.current_branch,'hotfix')
        run:
          python ${{env.VERSION_UPDATE_SCRIPT}} ${{ env.NAME_VERSION_FILE }} ${{ env.PATCH }}
      
      - name: Save Version and Log to env
        id: get-commit-txt
        run: | 
          COMMIT_MSG=$(python ${{env.VERSION_UPDATE_SCRIPT}} ${{ env.NAME_VERSION_FILE }} version_log -1)
          TAG_MSG=$(python ${{env.VERSION_UPDATE_SCRIPT}} ${{ env.NAME_VERSION_FILE }} version)
          echo "COMMIT_MSG=${COMMIT_MSG}" >> $GITHUB_ENV
          echo "TAG_MSG=${TAG_MSG}" >> $GITHUB_ENV
          echo "TAG_MSG=${TAG_MSG}" >> $GITHUB_OUTPUT

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Update version and put tag
        run: |
          git add .
          git commit -m "${{ env.COMMIT_MSG }}"
          git tag -a v${{ env.TAG_MSG }} -m "update tag"
          git push -u origin ${{ env.RELEASE_BRACH }} --tags