name: Security check
on:
  workflow_call:

jobs:
  antivirus:
    runs-on: ubuntu-latest
    name: Antivirus
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Run Git AV Scan
      uses: djdefi/gitavscan@main
      with:
        full: '--full'

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Run linter
        run: |
          echo "OK"

  deps-check:
    runs-on: ubuntu-latest
    name: Dependency check
    steps:
      - name: Run deps-checker
        run: |
          echo "OK"

  set-label:
    name: Set sec-passed label
    needs: [antivirus, lint, deps-check]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Set sec-passed label
        if: ${{ needs.antivirus.result == 'success' && needs.lint.result == 'success' && needs.deps-check.result == 'success' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['sec-passed']
            })