name: Test all
on:
  workflow_call:
    inputs:  
      version:
        type: string
        required: true

jobs:
  unit:
    name: Unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: |
          echo "simple run test"
  smoke:
    name: Smoke-test
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: |
          echo "simple run test"
  
  fazz:
    name: Fazzing
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: |
          echo "simple run test"

  integr:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: |
          echo "simple run test"

  regress:
    name: Regress
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: |
          echo "simple run test"

  set-label:
    name: Set test-passed label
    needs: [unit, smoke, fazz, integr, regress]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Set test-passed label
        if: ${{ needs.unit.result == 'success' && needs.smoke.result == 'success' && needs.fazz.result == 'success' && needs.integr.result == 'success' && needs.regress.result == 'success' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
              labels: ['test-passed']
            })